---
- name: parser meta data
  parser_metadata:
    version: 1.0
    command: show running-config
    network_os: ios

- name: match hostname
  pattern_match:
    regex: "^hostname ([^\\n]+)"
  register: ios_hostname
  export: yes

### interfaces ####
- name: capture interface subsection per interface
  pattern_match:
    regex: "!\\\n(interface [^!]+)\\\n"
    match_all: yes
  register: ios_net_interfaces_subset
  export: no

- name: match dot1x_count
  pattern_match:
    regex: "authentication control-direction ([^\\\n]+)"
    match_all: yes
  register: count_dot1x
  export: yes

- name: match totalports_count
  pattern_match:
    regex: "interface ([^\\\n]+)"
    match_all: yes
  register: count_totalports
  export: yes

- name: match openport_count
  pattern_match:
    regex: "\\n (authentication open)\\n"
    match_all: yes
  register: count_open
  export: yes

- name: match interface values
  pattern_group:
    - name: match name
      pattern_match:
        regex: "interface ([^\\\n]+)"
        content: "{{ item.matches }}"
      register: name

    - name: match description
      pattern_match:
        regex: "description ([^\\\n]+)"
        content: "{{ item.matches }}"
      register: description

    - name: match shutdown
      pattern_match:
        regex: "\\n (shutdown)\\n"
        content: "{{ item.matches  }}"
      register: shutdown

    - name: match dot1x
      pattern_match:
        regex: "authentication control-direction ([^\\\n]+)"
        content: "{{ item.matches }}"
      register: dot1x

    - name: match port open
      pattern_match:
        regex: "\\n (authentication open)\\n"
        content: "{{ item.matches }}"
      register: portopen

  loop: "{{ ios_net_interfaces_subset }}"
  register: ios_net_interfaces
  export: yes
